server:
  port: 8001

spring:
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: org.apache.commons.dbcp.PoolingDriver
   url: jdbc:mysql://47.93.232.76:3306/edu?useUnicode=true&characterEncoding=utf8&autoReconnect=true
   username: eduu
   password: ruejiaoyu


